export interface Produto {
	idArtigo: string | null,
    artigo: string,
    idMarca: number,
    idFornecedor: number,
    idCategoriaP: number,
    idFamilia: number,
    idSubFamilia: number,
    qt: number,
    stockloja: number,
    qtReservada: number,
    qtMin: number,
    custo: number,
    custoIVA: number,
    venda: number,
    vendaIVA: number,
    desconto: number,
    pvpWWW: number,
    margemAmadeus: number,
    vendaRevenda: number,
    IVA: number,
    peso: number,
    modelo: string,
    codigointerno: string,
    EAN: string,
    imgURL: string,
}